- name: setup app servers
  hosts: app_servers
  gather_facts: no

  tasks:
  - name: install SQL Server Management Studio with Chocolatey
    chocolatey.chocolatey.win_chocolatey:
      name: sql-server-management-studio
      state: present